---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-statefulset
  labels:
    db: mysql
  namespace: dev
spec:
  serviceName: mysql-svc
  minReadySeconds: 3
  replicas: 4
  selector:
    matchLabels:
      db: mysql-db
  updateStrategy:    
    type: RollingUpdate
    rollingUpdate:
      partition: 1
      maxUnavailable: 25%
  template:
    metadata:
      name: mysql-statefulset
      namespace: dev
      labels:
        db: mysql-db
    spec:
      containers:
        - name: mysql-pods
          image: mysql:8
          ports:
            - containerPort: 3306
              protocol: TCP 
              name: mysql-port
          envFrom:
            - secretRef:
                name: db-cred
                optional: false
          resources:
            requests:
              memory: "250Mi"
              cpu: "500m"
            limits:
              memory: "750Mi"
              cpu: "1000m"
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-vol     
  volumeClaimTemplates:
    - metadata:
        name: mysql-vol
      spec:
        accessModes: 
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: ebs-sc          
        
