apiVersion: v1
kind: Secret
metadata:
  name: db-cred
  namespace: dev
data:
  MYSQL_ROOT_PASSWORD: cm9vdC1yb290
  MYSQL_DATABASE: bXlzcWwtZGI=
  MYSQL_USER: bXlzcWwtdXNlcg==
  MYSQL_PASSWORD: bXlzcWwtcGFzc3dvcmQ=

# login  ::: mysql -u root -p then enter root password